### ISSUE TITLE
Bot Test Button throws error (but still works)

### ISSUE THREAD

**Issue by ejohnson3378** [v0idp/Mellow#101]
The bot is working in DM but in a server it is unable to respond - below is the error log:

```
TypeError: Cannot read property 'has' of undefined
at CommandoMessage.run (/usr/src/app/node_modules/discord.js-commando/src/extensions/message.js:125:65)
at CommandDispatcher.handleMessage (/usr/src/app/node_modules/discord.js-commando/src/dispatcher.js:143:32)
at BotClient.<anonymous> (/usr/src/app/node_modules/discord.js-commando/src/client.js:64:51)
at BotClient.emit (events.js:223:5)
at MessageCreateAction.handle (/usr/src/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
at Object.module.exports [as MESSAGE_CREATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:391:31)
at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:295:10)
at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:120:16)
at WebSocket.emit (events.js:223:5)
at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:800:20)
at Receiver.emit (events.js:223:5)
at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:423:14)
at Receiver.getData (/usr/src/app/node_modules/ws/lib/receiver.js:353:17)
at Receiver.startLoop (/usr/src/app/node_modules/ws/lib/receiver.js:139:22)
```

I am not familiar with Discord development so I am trying to set it up locally to test. I am running this in Docker.

**Comment by v0idp** [comment]
known issue. will fix this with the new switch to the new discord javascript library! been working on it already. in the meantime please use mellow in a native environment. docker images won't work until i reworked the codebase.

**Comment by v0idp** [comment]
Should be fixed in a901db3 let me know if you find any bugs.

**Comment by ejohnson3378** [comment]
just pulled v2.8.0 - this was output on the Test Connectivity button.  I am running this via the docker-compose in UnRaid. I also cleared the appdata and pulled again just to make sure there wasn't something left over, this problem persisted. 



```
TypeError: Cannot read property 'webConfig' of null
    at new DiscordBot (/usr/src/app/src/bots/discord/DiscordBot.js:12:26)
    at test (/usr/src/app/src/web/controllers/bot.js:7:15)
    at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at complete (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:268:13)
    at /usr/src/app/node_modules/passport/lib/middleware/authenticate.js:275:15
    at pass (/usr/src/app/node_modules/passport/lib/authenticator.js:431:14)
    at Authenticator.transformAuthInfo (/usr/src/app/node_modules/passport/lib/authenticator.js:453:5)
    at /usr/src/app/node_modules/passport/lib/middleware/authenticate.js:272:22
    at /usr/src/app/node_modules/passport/lib/http/request.js:52:7
    at /usr/src/app/node_modules/passport/lib/sessionmanager.js:26:5
    at pass (/usr/src/app/node_modules/passport/lib/authenticator.js:277:43)
    at serialized (/usr/src/app/node_modules/passport/lib/authenticator.js:286:7)
    at /usr/src/app/src/web/config/passport.js:23:5
```

looks like the `db` passed into the `Bot` is [null](https://github.com/v0idp/Mellow/blob/master/src/web/controllers/bot.js#L7)?

I am able to get the bot registered

`BotClient ready and logged in as MYBOT#### (**************). Prefix set to -. Use -help to view the commands list!`

**Comment by v0idp** [comment]
ah yes. The bot testing button doesn't pass a database object to the bot (it's not needed for testing the login) but apparently it throws an error. I will fix this. thanks for reporting !

**Comment by ejohnson3378** [comment]
Rest of the bot works great! let me know if ever want help.

**Comment by v0idp** [comment]
Fixed in 3e1fbbf
